name: Test that everything works

on:
  workflow_dispatch:
  push:
    branches:
      - pub
  pull_request:
    paths:
      - "**.py"

jobs:
  check_types:
    runs-on: ubuntu-latest
    name: Check Types
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - run: poetry install --with dev
      - run: poetry run pyright

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    name: Run Tests

    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - run: poetry install --with dev

      - name: Test
        run: poetry run coverage run -m pytest test/

  update-coverage:
    runs-on: ubuntu-latest
    name: Update Coverage

    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - run: poetry install --with dev

      - name: Test
        run: poetry run coverage run --include "gekkota/*" -m pytest test/

      - name: Coveralls update

        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
